language: java
jdk:
- oraclejdk8
dist: trusty
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
after_success:
- bash <(curl -s https://codecov.io/bash)
script:
- mvn install
deploy:
  provider: package
  api_key:
    secure: AF8SNOBHZUX6uOQDZGZNXMFo2x6axhO7mTSqM6pNtvCmqLDVca4fGn3Vt+GDhnKYTAqPNqv/5uWyW3zx0egg8Lb7h752u5zpo4fF9mKgzdDGn5OOV9mRTBglbL3obgnNRPfhrtQ/ns1R1tWhYFNmzwI7ac5cd5JoYJXVnkH8puwvqMX6gIkXxb6VeqGdP7GqoeJSRahlk8fjxQbOY2PMjOKkHOM337t0wmPaoC6tvdPKKM7oDU6OrkjSkwxpveLawmikn8tdi1WRJ77yI9Gcg1QqaxQFePCcfm9gW8LhVsPTFGvCphZCIaFaAmpYGMR3twAa9hcTbp9mDJljYudF00+G5OG/othqT0Vt1DjS0/KKdGBLdqyWneMWNLieCj+9eQfmsk36lzFcFlIpukDrueWRlp23go8y0XdzhV1xBjaL48XbBHRAbwMohr4hWPG2LVp5SLDFIav5rOudhbOSyoZJMkGlF5tb0WWe2p8A9LtwY+ysvP6mT4NtjoSzU5XpzwzRFGB7Zz677fNtkPBeeb3DzzB2ROdYLdpKADSHd1p5qa66Jx9RtoAS8pKdCfigEPWyPvj8WrPk29ChZzk2ML/0Vn0y6lqfVKxtJkaBs7Tj7m8V7RlgFMgqu/q/00oFkrLmYt19gyO6dJJ+kSSO0Sa7/IuFpCe0ETCfEUji1+A=
  file: target/grpc-jwt-spring-boot-starter-$project_version.jar
  on:
    repo: majusko/grpc-jwt-spring-boot-starter
