language: java
jdk:
- oraclejdk8
dist: trusty
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
after_success:
- bash <(curl -s https://codecov.io/bash)
script:
- mvn package
deploy:
  provider: releases
  api_key:
    secure: UPR5O48TmR2PxOi6aSRm3TifkNzuhrCrvVZ8RUpQj/q3BQDQAf21fqYaeqsDnlvkXR3IA4al17nzj74bZmzMvOQwm2b0wnhgh0zgSw96udXAKI1s6ZGAzxkoTtrvXxJZ5p0vOK0yyjQ1okZYDm+J9Gk7iaDnHQ/7Odwq3R84R+kIFG7w5XgeAM3njbHX9ksqVwCdCcEFU3FX5JlrlScQi50JnGZ4GxgZjQjavojZJ+HtfFS05rIGwhhJ/EEB5f0RqAFXwxgvm7bKSKv0pIb8ZMDPGzC6sI5Auo1uRQh15fFlNicLeT2Avx5jtJg98T+M2PzbEuuM2iZs1p1lVfKNDiDIJ/vWYQEfEQI5EnN9ROeubO8fV4fKnwZkb+sq8EC2RUN0J8hIy7ecN+w1e/O7jMLxwpp/MAACHaeI2PdNcYm4Y2nory0DfDhoyuFKvwwy3/wie5Qn8Aw5rQ66AQ2Ik2EuCEpT+ObgWP+6cmihgV/T2KiBwWM7vTMqV25BZQSMMDuYV8r59XBVdzDWTmz7WhBwbkKjd3GYFUZYJpbszIxCIqGErwVP+/6uWLvC1fHNKQm27MSEviopmkMlINdj38b1ma6kXGJHPIUq/GfCJgPDv5tADK56J/nM2Rl/K1vTeYdD1tIWUd7pjCxqKgHUM4paQrvpEtRD9soIs+N8eeU=
  file: target/grpc-jwt-spring-boot-starter-$project_version.jar
  on:
    repo: majusko/grpc-jwt-spring-boot-starter
